# Generated by Django 3.1.5 on 2021-01-21 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_usercart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='price',
        ),
    ]
